#!/bin/bash
# Fill missing translations for all locales

SUPABASE_URL="https://***REMOVED***"
ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhem1qZGp3bmtpbHljYmp3cHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIzNjU1MDcsImV4cCI6MjA0Nzk0MTUwN30.GKdXBxLPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP"

update_locale() {
  local locale=$1
  local translations=$2
  
  echo "Updating $locale..."
  curl -s -X POST "$SUPABASE_URL/functions/v1/update-translations" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $ANON_KEY" \
    -d "{\"locale\": \"$locale\", \"translations\": $translations}" | jq -r '.success // .error'
}

# Czech (cs) - 12 missing keys
CS_TRANSLATIONS='{
  "app": {"name": "Foodshare", "tagline": "Sdílejte jídlo. Snižte plýtvání. Budujte komunitu.", "links": {"help": "Centrum nápovědy", "terms": "Podmínky služby", "privacy": "Zásady ochrany osobních údajů"}, "safety": {"tip1": "Vždy se setkávejte na veřejných místech", "tip2": "Důvěřujte svým instinktům", "tip3": "Před přijetím zkontrolujte kvalitu jídla", "tip4": "Nahlaste podezřelou aktivitu"}, "safety_title": "Bezpečnostní připomínky", "mission_title": "Naše mise", "guidelines_title": "Pravidla komunity", "guidelines": {"safe_title": "Bezpečné setkání", "safe_desc": "Vybírejte veřejná, dobře osvětlená místa pro vyzvednutí", "report_title": "Nahlásit problémy", "report_desc": "Označte znepokojivé nabídky nebo chování", "respectful_title": "Buďte ohleduplní", "respectful_desc": "Chovejte se ke všem členům komunity s laskavostí a respektem", "communicate_title": "Komunikujte jasně", "communicate_desc": "Odpovídejte na zprávy včas a dodržujte své závazky", "responsible_title": "Sdílejte zodpovědně", "responsible_desc": "Sdílejte pouze bezpečné, kvalitní jídlo"}},
  "challenge": {"title": "Výzvy", "likes": "Líbí se", "shuffle": "Zamíchat", "be_first": "Buďte první!", "no_leaders": "Zatím žádní lídři. Buďte první!", "pick_title": "Vyberte si výzvu", "swipe_hint": "Přejeďte doprava pro připojení, doleva pro přeskočení", "your_status": "Váš stav", "completed_by": "Dokončeno", "pick_subtitle": "Procházejte nebo klepněte pro prozkoumání", "your_progress": "Váš pokrok", "no_completions": "Zatím nikdo nedokončil", "top_challengers": "Nejlepší vyzyvatelé", "card": {"face_down": "Výzva"}, "action": {"join": "PŘIPOJIT", "skip": "PŘESKOČIT", "accept": "Přijmout výzvu", "completed": "Výzva dokončena!", "mark_complete": "Označit jako dokončené", "sign_in_accept": "Přihlaste se pro přijetí výzvy"}, "status": {"new": "Nové", "done": "Hotovo", "join": "Připojit", "skip": "Přeskočit", "active": "Aktivní", "declined": "Odmítnuto", "available": "Dostupné", "completed": "Dokončeno", "in_progress": "Probíhá"}, "widget": {"title": "Výzva", "active": "Aktivní výzva", "complete": "DOKONČIT", "days_left": "dní zbývá", "no_active": "Žádná aktivní výzva", "start_hint": "Začněte výzvu v aplikaci!", "day_left_short": "d zbývá"}, "leaderboard": {"title": "Žebříček", "copy": "Kopírovat", "share": "Sdílet úspěch", "cancel": "Zrušit", "empty_title": "Zatím žádní lídři", "empty_desc": "Buďte první na žebříčku!"}},
  "chats": {"title": "Chaty", "send": "Odeslat", "loading": "Načítání zpráv...", "no_messages": "Zatím žádné zprávy", "type_message": "Napište zprávu..."},
  "common": {"no": "Ne", "ok": "OK", "yes": "Ano", "back": "Zpět", "copy": "Kopírovat", "done": "Hotovo", "edit": "Upravit", "next": "Další", "open": "Otevřít {title}", "save": "Uložit", "send": "Odeslat", "skip": "Přeskočit", "block": "Blokovat", "close": "Zavřít", "error": "Chyba", "retry": "Opakovat", "share": "Sdílet", "cancel": "Zrušit", "copied": "Zkopírováno!", "delete": "Smazat", "filter": "Filtr", "period": "Období", "report": "Nahlásit", "search": "Hledat", "submit": "Odeslat", "confirm": "Potvrdit", "loading": "Načítání...", "refresh": "Obnovit", "see_all": "Zobrazit vše", "sort_by": "Řadit podle", "success": "Úspěch", "continue": "Pokračovat", "view_all": "Zobrazit vše", "show_less": "Zobrazit méně", "show_more": "Zobrazit více", "try_again": "Zkusit znovu", "learn_more": "Zjistit více", "no_results": "Žádné výsledky", "submitting": "Odesílání...", "get_started": "Začít", "privacy_policy": "Zásady ochrany osobních údajů", "terms_of_service": "Podmínky služby"},
  "errors": {"title": "Chyba", "network": "Chyba sítě. Zkontrolujte připojení.", "unknown": "Došlo k neznámé chybě", "not_found": {"title": "Nenalezeno", "post": "Příspěvek nenalezen", "listing": "Nabídka nenalezena", "profile": "Profil nenalezen", "challenge": "Výzva nenalezena", "post_desc": "Tento příspěvek mohl být odstraněn.", "listing_desc": "Tato nabídka mohla být odstraněna.", "profile_desc": "Tento profil neexistuje.", "challenge_desc": "Tato výzva mohla skončit."}, "no_results": {"title": "Žádné výsledky", "description": "Zkuste jiný hledaný výraz"}},
  "guest": {"banner": {"title": "Procházíte jako host", "action": "Registrovat", "subtitle": "Zaregistrujte se pro odemknutí všech funkcí"}, "prompt": {"title": "Přihlaste se k {feature}", "action": "Přihlásit"}, "restricted": {"title": "Vyžadováno přihlášení", "action": "Vytvořit účet zdarma", "message": "Vytvořte si účet zdarma pro odemknutí této funkce", "secondary": "Pokračovat v prohlížení"}},
  "insights": {"title": "Přehledy", "likes": "Líbí se", "views": "Zobrazení", "points": "body", "shared": "Sdíleno", "messages": "Zprávy", "received": "Přijato", "my_impact": "Můj dopad", "food_saved": "Zachráněné jídlo", "best_streak": "Nejlepší série", "money_saved": "Ušetřené peníze", "water_saved": "Ušetřená voda", "impact_score": "Skóre dopadu", "success_rate": "Úspěšnost", "co2_prevented": "Zabráněno CO2", "current_streak": "Aktuální série", "making_difference": "Děláte rozdíl!", "environmental_impact": "Dopad na životní prostředí", "period": {"week": "Tento týden", "month": "Tento měsíc", "year": "Tento rok", "all_time": "Celkem"}},
  "map": {"away": "daleko", "clear": "Vymazat", "retry": "Opakovat", "views": "Zobrazení", "nearby": "Poblíž", "pickup": "Vyzvednutí", "set_to": "Nastavit na {location}", "distance": "Vzdálenost", "location": "Poloha", "settings": "Nastavení", "enable_gps": "Povolit GPS", "food_details": "Detaily jídla", "gps_location": "GPS poloha (±{accuracy}m)", "items_nearby": "{count} položek poblíž", "request_item": "Požádat o položku", "people_viewed": "{count} lidí zobrazilo", "pan_to_explore": "Posuňte mapu pro prozkoumání", "rough_location": "Přibližná poloha", "custom_location": "Vlastní poloha", "location_denied": "Přístup k poloze zamítnut", "approximate_location": "Přibližná poloha", "very_approximate_location": "Velmi přibližná poloha", "status": {"active": "Aktivní", "arranged": "Domluveno", "inactive": "Neaktivní"}},
  "navigation": {"chat": "Chat", "search": "Hledat", "details": "Detaily", "filters": "Filtry", "history": "Historie", "reviews": "Recenze", "new_post": "Nový příspěvek", "settings": "Nastavení", "discussion": "Diskuze", "help_center": "Centrum nápovědy", "my_listings": "Moje nabídky", "report_item": "Nahlásit položku", "report_post": "Nahlásit příspěvek", "saved_posts": "Uložené příspěvky", "choose_theme": "Vybrat motiv", "edit_comment": "Upravit komentář", "edit_profile": "Upravit profil", "report_issue": "Nahlásit problém", "blocked_users": "Blokovaní uživatelé", "notifications": "Oznámení", "share_profile": "Sdílet profil", "contact_sharer": "Kontaktovat sdílejícího", "invite_friends": "Pozvat přátele", "privacy_policy": "Zásady ochrany osobních údajů", "reset_password": "Obnovit heslo", "sync_conflicts": "Konflikty synchronizace", "select_category": "Vybrat kategorii", "account_settings": "Nastavení účtu", "filters_settings": "Filtry a nastavení", "privacy_settings": "Nastavení soukromí", "resolve_conflict": "Vyřešit konflikt", "terms_of_service": "Podmínky služby", "community_fridges": "Komunitní lednice", "email_preferences": "Předvolby e-mailu", "select_date_range": "Vybrat období", "support_foodshare": "Podpořit Foodshare", "notification_settings": "Nastavení oznámení"},
  "onboarding": {"welcome": "Vítejte ve Foodshare", "tagline": "Sdílejte jídlo, snižte plýtvání, pomozte své komunitě", "terms": "Podmínky", "privacy": "Soukromí", "apple_eula": "Apple EULA", "legal_info": "Důležité právní informace", "agree_continue": "Souhlasím a pokračovat", "important_info": "Důležité informace", "read_disclaimer": "Přečíst prohlášení", "platform_disclaimer": "Prohlášení platformy"},
  "reviews": {"title": "Recenze", "helpful": "Užitečné", "no_reviews": "Zatím žádné recenze", "all_reviews": "Všechny recenze", "review_count": "{count} recenzí", "write_review": "Napsat recenzi", "report_review": "Nahlásit recenzi", "submit_review": "Odeslat recenzi", "your_feedback": "Vaše zpětná vazba", "how_was_experience": "Jaká byla vaše zkušenost?", "sort": {"newest": "Nejnovější", "oldest": "Nejstarší", "lowest_rating": "Nejnižší hodnocení", "highest_rating": "Nejvyšší hodnocení"}},
  "tabs": {"chats": "Chaty", "forum": "Fórum", "explore": "Prozkoumat", "profile": "Profil", "challenges": "Výzvy"}
}'

update_locale "cs" "$CS_TRANSLATIONS"

# German (de) - 19 missing keys  
DE_TRANSLATIONS='{
  "app": {"name": "Foodshare", "tagline": "Teile Essen. Reduziere Verschwendung. Baue Gemeinschaft.", "links": {"help": "Hilfezentrum", "terms": "Nutzungsbedingungen", "privacy": "Datenschutzrichtlinie"}, "safety": {"tip1": "Treffen Sie sich immer an öffentlichen Orten", "tip2": "Vertrauen Sie Ihrem Instinkt", "tip3": "Überprüfen Sie die Lebensmittelqualität vor der Annahme", "tip4": "Melden Sie verdächtige Aktivitäten"}, "safety_title": "Sicherheitshinweise", "mission_title": "Unsere Mission", "guidelines_title": "Community-Richtlinien", "guidelines": {"safe_title": "Sicher treffen", "safe_desc": "Wählen Sie öffentliche, gut beleuchtete Orte für Abholungen", "report_title": "Probleme melden", "report_desc": "Markieren Sie besorgniserregende Angebote oder Verhalten", "respectful_title": "Respektvoll sein", "respectful_desc": "Behandeln Sie alle Community-Mitglieder mit Freundlichkeit und Respekt", "communicate_title": "Klar kommunizieren", "communicate_desc": "Antworten Sie zeitnah auf Nachrichten und halten Sie Ihre Zusagen ein", "responsible_title": "Verantwortungsvoll teilen", "responsible_desc": "Teilen Sie nur sichere, qualitativ hochwertige Lebensmittel"}},
  "challenge": {"title": "Herausforderungen", "likes": "Gefällt mir", "shuffle": "Mischen", "be_first": "Sei der Erste!", "no_leaders": "Noch keine Anführer. Sei der Erste!", "pick_title": "Wähle deine Herausforderung", "swipe_hint": "Nach rechts wischen zum Beitreten, nach links zum Überspringen", "your_status": "Dein Status", "completed_by": "Abgeschlossen von", "pick_subtitle": "Durchblättern oder tippen zum Erkunden", "your_progress": "Dein Fortschritt", "no_completions": "Noch niemand hat abgeschlossen", "top_challengers": "Top-Herausforderer", "card": {"face_down": "Herausforderung"}, "action": {"join": "BEITRETEN", "skip": "ÜBERSPRINGEN", "accept": "Herausforderung annehmen", "completed": "Herausforderung abgeschlossen!", "mark_complete": "Als abgeschlossen markieren", "sign_in_accept": "Anmelden um Herausforderung anzunehmen"}, "status": {"new": "Neu", "done": "Fertig", "join": "Beitreten", "skip": "Überspringen", "active": "Aktiv", "declined": "Abgelehnt", "available": "Verfügbar", "completed": "Abgeschlossen", "in_progress": "In Bearbeitung"}, "widget": {"title": "Herausforderung", "active": "Aktive Herausforderung", "complete": "ABSCHLIESSEN", "days_left": "Tage übrig", "no_active": "Keine aktive Herausforderung", "start_hint": "Starte eine Herausforderung in der App!", "day_left_short": "T übrig"}, "leaderboard": {"title": "Bestenliste", "copy": "Kopieren", "share": "Erfolg teilen", "cancel": "Abbrechen", "empty_title": "Noch keine Anführer", "empty_desc": "Sei der Erste auf der Bestenliste!"}},
  "chats": {"title": "Chats", "send": "Senden", "loading": "Nachrichten werden geladen...", "no_messages": "Noch keine Nachrichten", "type_message": "Nachricht eingeben..."},
  "errors": {"title": "Fehler", "network": "Netzwerkfehler. Bitte überprüfen Sie Ihre Verbindung.", "unknown": "Ein unbekannter Fehler ist aufgetreten", "not_found": {"title": "Nicht gefunden", "post": "Beitrag nicht gefunden", "listing": "Angebot nicht gefunden", "profile": "Profil nicht gefunden", "challenge": "Herausforderung nicht gefunden", "post_desc": "Dieser Beitrag wurde möglicherweise entfernt.", "listing_desc": "Dieses Angebot wurde möglicherweise entfernt.", "profile_desc": "Dieses Profil existiert möglicherweise nicht.", "challenge_desc": "Diese Herausforderung ist möglicherweise beendet."}, "no_results": {"title": "Keine Ergebnisse", "description": "Versuchen Sie einen anderen Suchbegriff"}},
  "guest": {"banner": {"title": "Als Gast browsen", "action": "Registrieren", "subtitle": "Registrieren Sie sich, um alle Funktionen freizuschalten"}, "prompt": {"title": "Anmelden für {feature}", "action": "Anmelden"}, "restricted": {"title": "Anmeldung erforderlich", "action": "Kostenloses Konto erstellen", "message": "Erstellen Sie ein kostenloses Konto, um diese Funktion freizuschalten", "secondary": "Weiter erkunden"}},
  "map": {"away": "entfernt", "clear": "Löschen", "retry": "Wiederholen", "views": "Aufrufe", "nearby": "In der Nähe", "pickup": "Abholung", "set_to": "Setzen auf {location}", "distance": "Entfernung", "location": "Standort", "settings": "Einstellungen", "enable_gps": "GPS aktivieren", "food_details": "Lebensmitteldetails", "gps_location": "GPS-Standort (±{accuracy}m)", "items_nearby": "{count} Artikel in der Nähe", "request_item": "Artikel anfragen", "people_viewed": "{count} Personen haben angesehen", "pan_to_explore": "Karte verschieben zum Erkunden", "rough_location": "Ungefährer Standort", "custom_location": "Benutzerdefinierter Standort", "location_denied": "Standortzugriff verweigert", "approximate_location": "Ungefährer Standort", "very_approximate_location": "Sehr ungefährer Standort", "status": {"active": "Aktiv", "arranged": "Vereinbart", "inactive": "Inaktiv"}},
  "navigation": {"chat": "Chat", "search": "Suchen", "details": "Details", "filters": "Filter", "history": "Verlauf", "reviews": "Bewertungen", "new_post": "Neuer Beitrag", "settings": "Einstellungen", "discussion": "Diskussion", "help_center": "Hilfezentrum", "my_listings": "Meine Angebote", "report_item": "Artikel melden", "report_post": "Beitrag melden", "saved_posts": "Gespeicherte Beiträge", "choose_theme": "Design wählen", "edit_comment": "Kommentar bearbeiten", "edit_profile": "Profil bearbeiten", "report_issue": "Problem melden", "blocked_users": "Blockierte Benutzer", "notifications": "Benachrichtigungen", "share_profile": "Profil teilen", "contact_sharer": "Teiler kontaktieren", "invite_friends": "Freunde einladen", "privacy_policy": "Datenschutzrichtlinie", "reset_password": "Passwort zurücksetzen", "sync_conflicts": "Synchronisierungskonflikte", "select_category": "Kategorie wählen", "account_settings": "Kontoeinstellungen", "filters_settings": "Filter & Einstellungen", "privacy_settings": "Datenschutzeinstellungen", "resolve_conflict": "Konflikt lösen", "terms_of_service": "Nutzungsbedingungen", "community_fridges": "Gemeinschaftskühlschränke", "email_preferences": "E-Mail-Einstellungen", "select_date_range": "Zeitraum wählen", "support_foodshare": "Foodshare unterstützen", "notification_settings": "Benachrichtigungseinstellungen"},
  "tabs": {"chats": "Chats", "forum": "Forum", "explore": "Entdecken", "profile": "Profil", "challenges": "Herausforderungen"},
  "ChallengeReveal": {"tip": "Tipp: Pfeiltasten oder Ziehen zum Durchblättern", "skip": "Überspringen", "title": "Herausforderungen entdecken", "accept": "Annehmen", "shuffle": "Mischen", "subtitle": "Nach rechts wischen zum Annehmen, nach links zum Überspringen", "allCaughtUp": "Alles erledigt!", "shuffleAgain": "Erneut mischen", "keyboardHints": {"skip": "Überspringen", "close": "Schließen", "accept": "Annehmen"}, "discoverRandom": "Zufällig entdecken", "acceptingChallenge": "Herausforderung wird angenommen...", "challengesRemaining": "{count} Herausforderungen übrig", "allCaughtUpDescription": "Du hast alle Herausforderungen gesehen. Mische das Deck, um sie erneut durchzugehen!"},
  "Common": {"dismiss": "Schließen", "refresh": "Status prüfen", "maintenanceMessage": "Wir führen geplante Wartungsarbeiten durch. Einige Funktionen sind möglicherweise vorübergehend nicht verfügbar."},
  "ForgotPassword": {"title": "Passwort vergessen?", "description": "Keine Sorge! Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen.", "back_to_login": "Zurück zur Anmeldung", "didnt_receive": "E-Mail nicht erhalten? Überprüfen Sie Ihren Spam-Ordner oder", "error_generic": "Fehler beim Senden der E-Mail. Bitte versuchen Sie es erneut.", "return_to_login": "Zurück zur Anmeldung", "send_reset_link": "Link senden", "check_email_title": "Überprüfen Sie Ihre E-Mail", "remember_password": "Passwort gemerkt?", "check_email_description": "Wir haben einen Link zum Zurücksetzen gesendet an"},
  "Maintenance": {"title": "Wartung", "contact": "Hilfe benötigt? Kontaktieren Sie uns unter support@foodshare.club", "refresh": "Status aktualisieren", "description": "Wir führen geplante Wartungsarbeiten durch. Bitte versuchen Sie es später erneut.", "lastChecked": "Zuletzt geprüft", "redirecting": "Weiterleitung...", "serviceStatus": "Servicestatus", "allSystemsOperational": "Alle Systeme funktionieren!"},
  "email_templates_coming_soon": "E-Mail-Vorlagen-Verwaltung kommt bald...",
  "forum_no_posts_desc": "Versuchen Sie, Ihre Filter anzupassen oder seien Sie der Erste, der postet!",
  "forum_quick_actions_idea_desc": "Eine Diskussion starten",
  "forum_quick_actions_question_desc": "Hilfe erhalten",
  "leave_as_autoselect_to_use_smart_routing_based_on_quota_availability": "Lassen Sie \"Automatisch\" für intelligentes Routing basierend auf Verfügbarkeit",
  "rate_count_of_total_stars": "Bewerten Sie {count} von {total} Sternen",
  "test_direct": "Direkt testen (Resend)"
}'

update_locale "de" "$DE_TRANSLATIONS"

echo "Done with cs and de. Run additional scripts for remaining locales."
