-- ============================================================================
-- Email Provider Health Metrics Table
-- Real-time health tracking for email providers (synced from provider APIs)
-- ============================================================================

-- Drop existing table to recreate with proper schema
-- Data is regenerated by sync process
DROP TABLE IF EXISTS email_provider_health_metrics CASCADE;

-- Create the health metrics table
CREATE TABLE email_provider_health_metrics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  provider text NOT NULL UNIQUE,

  -- Health metrics
  health_score integer NOT NULL DEFAULT 100,
  total_requests integer NOT NULL DEFAULT 0,
  successful_requests integer NOT NULL DEFAULT 0,
  failed_requests integer NOT NULL DEFAULT 0,
  average_latency_ms integer NOT NULL DEFAULT 0,

  -- Circuit breaker state
  circuit_state text DEFAULT 'closed' CHECK (circuit_state IN ('closed', 'open', 'half-open')),
  consecutive_failures integer NOT NULL DEFAULT 0,
  last_failure_at timestamptz,
  last_success_at timestamptz,

  -- Quota info (synced from provider APIs)
  daily_quota_used integer NOT NULL DEFAULT 0,
  daily_quota_limit integer NOT NULL DEFAULT 500,
  monthly_quota_used integer NOT NULL DEFAULT 0,
  monthly_quota_limit integer NOT NULL DEFAULT 15000,

  -- Provider-specific stats
  emails_delivered integer NOT NULL DEFAULT 0,
  emails_opened integer NOT NULL DEFAULT 0,
  emails_clicked integer NOT NULL DEFAULT 0,
  emails_bounced integer NOT NULL DEFAULT 0,
  emails_complained integer NOT NULL DEFAULT 0,

  -- Timestamps
  last_updated timestamptz NOT NULL DEFAULT now(),
  last_synced_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_email_provider_health_provider
  ON email_provider_health_metrics(provider);

-- Insert default rows for all providers
INSERT INTO email_provider_health_metrics (provider, daily_quota_limit, monthly_quota_limit)
VALUES
  ('resend', 100, 3000),
  ('brevo', 300, 9000),
  ('mailersend', 400, 12000),
  ('aws_ses', 50000, 62000)
ON CONFLICT (provider) DO NOTHING;

-- ============================================================================
-- Function to record email send and update health metrics
-- Called by Edge Functions after each email send
-- ============================================================================

CREATE OR REPLACE FUNCTION record_email_send(
  p_provider text,
  p_success boolean,
  p_latency_ms integer DEFAULT 0,
  p_message_id text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Update health metrics
  INSERT INTO email_provider_health_metrics (
    provider,
    total_requests,
    successful_requests,
    failed_requests,
    average_latency_ms,
    daily_quota_used,
    consecutive_failures,
    last_success_at,
    last_failure_at,
    last_updated
  )
  VALUES (
    p_provider,
    1,
    CASE WHEN p_success THEN 1 ELSE 0 END,
    CASE WHEN p_success THEN 0 ELSE 1 END,
    p_latency_ms,
    CASE WHEN p_success THEN 1 ELSE 0 END,
    CASE WHEN p_success THEN 0 ELSE 1 END,
    CASE WHEN p_success THEN now() ELSE NULL END,
    CASE WHEN NOT p_success THEN now() ELSE NULL END,
    now()
  )
  ON CONFLICT (provider) DO UPDATE SET
    total_requests = email_provider_health_metrics.total_requests + 1,
    successful_requests = email_provider_health_metrics.successful_requests + CASE WHEN p_success THEN 1 ELSE 0 END,
    failed_requests = email_provider_health_metrics.failed_requests + CASE WHEN p_success THEN 0 ELSE 1 END,
    average_latency_ms = CASE
      WHEN email_provider_health_metrics.total_requests > 0
      THEN ((email_provider_health_metrics.average_latency_ms * email_provider_health_metrics.total_requests + p_latency_ms) / (email_provider_health_metrics.total_requests + 1))::integer
      ELSE p_latency_ms
    END,
    daily_quota_used = email_provider_health_metrics.daily_quota_used + CASE WHEN p_success THEN 1 ELSE 0 END,
    consecutive_failures = CASE
      WHEN p_success THEN 0
      ELSE email_provider_health_metrics.consecutive_failures + 1
    END,
    health_score = CASE
      WHEN p_success THEN LEAST(100, email_provider_health_metrics.health_score + 5)
      ELSE GREATEST(0, email_provider_health_metrics.health_score - 10)
    END,
    last_success_at = CASE WHEN p_success THEN now() ELSE email_provider_health_metrics.last_success_at END,
    last_failure_at = CASE WHEN NOT p_success THEN now() ELSE email_provider_health_metrics.last_failure_at END,
    last_updated = now();

  -- Also update email_provider_stats for historical tracking
  PERFORM increment_email_provider_stats(p_provider, p_success, p_latency_ms);
END;
$$;

-- ============================================================================
-- Function to sync provider stats from external API calls
-- Called by sync-email-provider-stats Edge Function
-- ============================================================================

CREATE OR REPLACE FUNCTION sync_provider_health(
  p_provider text,
  p_health_score integer,
  p_latency_ms integer,
  p_daily_used integer DEFAULT 0,
  p_daily_limit integer DEFAULT 500,
  p_monthly_used integer DEFAULT 0,
  p_monthly_limit integer DEFAULT 15000,
  p_delivered integer DEFAULT 0,
  p_opened integer DEFAULT 0,
  p_clicked integer DEFAULT 0,
  p_bounced integer DEFAULT 0,
  p_complained integer DEFAULT 0
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO email_provider_health_metrics (
    provider,
    health_score,
    average_latency_ms,
    daily_quota_used,
    daily_quota_limit,
    monthly_quota_used,
    monthly_quota_limit,
    emails_delivered,
    emails_opened,
    emails_clicked,
    emails_bounced,
    emails_complained,
    last_synced_at,
    last_updated
  )
  VALUES (
    p_provider,
    p_health_score,
    p_latency_ms,
    p_daily_used,
    p_daily_limit,
    p_monthly_used,
    p_monthly_limit,
    p_delivered,
    p_opened,
    p_clicked,
    p_bounced,
    p_complained,
    now(),
    now()
  )
  ON CONFLICT (provider) DO UPDATE SET
    health_score = p_health_score,
    average_latency_ms = p_latency_ms,
    daily_quota_used = p_daily_used,
    daily_quota_limit = p_daily_limit,
    monthly_quota_used = p_monthly_used,
    monthly_quota_limit = p_monthly_limit,
    emails_delivered = p_delivered,
    emails_opened = p_opened,
    emails_clicked = p_clicked,
    emails_bounced = p_bounced,
    emails_complained = p_complained,
    last_synced_at = now(),
    last_updated = now();
END;
$$;

-- ============================================================================
-- Function to reset daily quotas (call at midnight)
-- ============================================================================

CREATE OR REPLACE FUNCTION reset_daily_email_quotas()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE email_provider_health_metrics
  SET
    daily_quota_used = 0,
    last_updated = now();

  UPDATE email_provider_stats
  SET
    emails_sent = 0,
    requests_total = 0,
    requests_success = 0,
    requests_failed = 0,
    updated_at = now()
  WHERE date < CURRENT_DATE;
END;
$$;

-- ============================================================================
-- RLS Policies
-- ============================================================================

ALTER TABLE email_provider_health_metrics ENABLE ROW LEVEL SECURITY;

-- Admins can view health metrics
DROP POLICY IF EXISTS "Admins can view email provider health metrics" ON email_provider_health_metrics;
CREATE POLICY "Admins can view email provider health metrics"
  ON email_provider_health_metrics FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON r.id = ur.role_id
      WHERE ur.profile_id = auth.uid()
      AND r.name IN ('admin', 'superadmin')
    )
  );

-- Service role can do everything
DROP POLICY IF EXISTS "Service role full access to health metrics" ON email_provider_health_metrics;
CREATE POLICY "Service role full access to health metrics"
  ON email_provider_health_metrics FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ============================================================================
-- Permissions
-- ============================================================================

GRANT SELECT ON email_provider_health_metrics TO authenticated;
GRANT ALL ON email_provider_health_metrics TO service_role;
GRANT EXECUTE ON FUNCTION record_email_send TO service_role;
GRANT EXECUTE ON FUNCTION sync_provider_health TO service_role;
GRANT EXECUTE ON FUNCTION reset_daily_email_quotas TO service_role;

-- ============================================================================
-- Comments
-- ============================================================================

COMMENT ON TABLE email_provider_health_metrics IS
  'Real-time health metrics for email providers, synced from provider APIs';

COMMENT ON FUNCTION record_email_send IS
  'Records an email send attempt and updates provider health metrics';

COMMENT ON FUNCTION sync_provider_health IS
  'Syncs provider health data from external API calls (used by sync-email-provider-stats)';

COMMENT ON FUNCTION reset_daily_email_quotas IS
  'Resets daily quota counters, should be called at midnight via cron';
